theme: jekyll-theme-hacker





github:
  is_project_page: false
 
 <!-- HEADER -->
    <div id="header_wrap" class="outer">
        <header class="inner">
          <a id="forkme_banner" href="{{ site.github.repository_url }}">View on GitHub</a>
          {% if site.github.is_project_page %}
            <a id="forkme_banner" href="{{ site.github.repository_url }}">View on GitHub</a>
          {% endif %}

